### ISSUE TITLE
redis类型stream流加载不出来

### ISSUE THREAD

**Issue by huxxhua** [liuzhuoling2011/RedisGo#13]
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/20944512/148203779-35c2f415-021c-42d7-bc9f-f3be295ba885.png">

麻烦大大抽空看看，打算用到生成环境。
最近也在学习go，学习下，最后感谢这个项目的开源，很棒。

**Comment by liuzhuoling2011** [comment]
好的, 这个应该是设计的时候没有考虑的一个类型, 我之后加上

**Comment by huxxhua** [comment]
好的，谢谢大佬。
