### ISSUE TITLE
建议：提供前端部分源码

### ISSUE THREAD

**Issue by zqhong** [liuzhuoling2011/RedisGo#4]
你好，我看了下源码，只提供了处理过的前端资源（`web/dist` 目录），希望你能开源 RedisGo 前端部分的代码。

这样的好处：
1. 用户可以更全面地定制界面
2. 社区用户可以帮忙一起完善前端功能

最后，非常感谢你开源 RedisGo 这个工具，解决了我对于监控 Redis 的需求。:+1:

**Comment by liuzhuoling2011** [comment]
Thanks 支持 ♪(･ω･)ﾉ
我之后会开源的

**Comment by licc** [comment]
源码不开放了吗？

**Comment by bdqnaccphantianyang** [comment]
请问一下，添加错误, 请检查redis配置是否重复或者不正确，这个是只能添加本地电脑起的redis吗，不能添加别人的电脑起的redis吗

**Comment by liuzhuoling2011** [comment]
会全部开源的, 工作太忙了, 还没来得及处理

**Comment by liuzhuoling2011** [comment]
RedisGo 的前端源码已经放出来了
https://github.com/liuzhuoling2011/RedisGo-Web
