### ISSUE TITLE
在一台机器上部署了多个redis之后, 添加连接会有问题

### ISSUE THREAD

**Issue by Stepkim** [liuzhuoling2011/RedisGo#5]
当单台机器部署了多个redis实例之后, 如果添加连接, 只能添加第一个, 后面的会因为ip相同而无法添加成功, 看了一下源码, 比对的时候是通过ip进行比对的, 我觉得可以考虑改成通过ip+port+db组合来当作map的key.
       
        能否开源前端代码方便进行定制功能?

**Comment by liuzhuoling2011** [comment]
前端代码一直没来得及整理, 周末我先帮你改了这个功能吧

**Comment by liuzhuoling2011** [comment]
@Stepkim 已经更新版本, 详情请见Release
